package br.com.phricardo.mockecomm.entities;

public enum ProductCategoryEnum {
  ELECTRONICS,
  CLOTHING,
  HOME_AND_KITCHEN,
  BEAUTY_AND_PERSONAL_CARE,
  SPORTS_AND_OUTDOORS,
  BOOKS_AND_MEDIA,
  TOYS_AND_GAMES,
  HEALTH_AND_WELLNESS,
  FOOD_AND_DRINK,
  AUTOMOTIVE,
  PETS,
  OFFICE_AND_SCHOOL_SUPPLIES,
  JEWELRY_AND_ACCESSORIES,
  OTHER
}
